### ISSUE TITLE
No tensorflow framework library in libtensorflow-cpu-windows-x86_64-1.15.0.zip

### ISSUE THREAD

**Issue by PRPoundSix** [gvne/spleeterpp#17]
The precompiled tensorflow library for Windows only has the tensorflow.lib and .dll. It looks like the framework dll/lib is not needed on Windows platform to successfully build projects and during runtime executions.

`CMake Error at cmake/add_tensorflow.cmake:52 (message):
  Tensorflow could not be included`

**Comment by gvne** [comment]
Hi @PRPoundSix thank you for your feedback. You are trying the develop branch for windows right ? I didn't check the windows compatibility for windows yet for the latest developments. If you are not interested in the filter interface, I would suggest falling back to the latest release.

I don't have enough time to work on this at the moment but will address this as soon as possible. If you feel like it, I do accept pull requests 😄

**Comment by PRPoundSix** [comment]
Hi Guillaume,
I tried the master branch and although the build is good. I got the following error when running the 2 stem test on Windows:

Running main() from gtest_main.cc[==========] Running 1 test from 1 test case.[----------] Global test environment set-up.[----------] 1 test from Spleeter[ RUN      ] Spleeter.TwoStems2020-04-26 14:24:57.956072: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from:unknown file: error: C++ exception with description "bad allocation" thrown in the test body.[  FAILED  ] Spleeter.TwoStems (187 ms)[----------] 1 test from Spleeter (187 ms total)
[----------] Global test environment tear-down[==========] 1 test from 1 test case ran. (192 ms total)[  PASSED  ] 0 tests.[  FAILED  ] 1 test, listed below:[  FAILED  ] Spleeter.TwoStems
 1 FAILED TEST
C:\repos\spleeterpp\build\test\spleeter\Debug\test_spleeter.exe (process 4668) exited with code 1.Press any key to close this window . . .

I tried to fix the problem but the couldn't figure out why allocation is bad.
I can successfully run the same test on the develop branch though (after some adjustments related to the issue I reported.) I may create a pull request for the develop branch later but I am both new to TensorFlow and also CMake so I need time to get familiar with both. 
Thanks for the shared code.
    On Sunday, April 26, 2020, 05:32:50 AM EDT, Guillaume Vincke <notifications@github.com> wrote:  
 
 


Hi @PRPoundSix thank you for your feedback. You are trying the develop branch for windows right ? I didn't check the windows compatibility for windows yet for the latest developments. If you are not interested in the filter interface, I would suggest falling back to the latest release.

I don't have enough time to work on this at the moment but will address this as soon as possible. If you feel like it, I do accept pull requests 😄

**Comment by aidv** [comment]
I'm getting the same error as OP.

@gvne care to point us in the right direction? What is the core issue and were *could* it be fixed? I'll have a look at it.

**Comment by gvne** [comment]
Hi there, sorry for the delay. 
I just pushed a fix for windows on the develop branch. However, the filter interface doesn't seem to give the right results. That being said you should be able to use the classic interface (not real time) successfully now

**Comment by gvne** [comment]
It seems like the problem comes from the asynchronous process of frames.  
To avoid multiple thread to use the temporary buffers, even if each frame is computed in a separated frame, the process has to be done sequentially. I am using an std::mutex to force this. However, it seems that it [std::mutex does not ensure this](https://stackoverflow.com/questions/41847511/is-stdmutex-sequentially-consistent).  
I will try using  event objects as suggested [here](https://stackoverflow.com/questions/19715873/how-to-force-threads-to-work-in-strict-order). 

In the meantime, if you really want to use the filter interface, just set the `extra_frame_latency` to zero and you'll be fine.

**Comment by gvne** [comment]
Using a semaphore is better than mutex to keep the sequential aspect. I added a semaphore implementation (using std::mutex and std::condition_variable) that fixed the issue.  
I also integrated the Appveyor CI to avoid that kind of issue in the future !
