### ISSUE TITLE
Can anyone help me to run spleeter in 16 kHz mode on my mac?  i think you have to type something into the terminal but i can't find any clear instructions anywhere.   Thanks.

### ISSUE THREAD

**Issue by Jstonebeats1** [gvne/spleeterpp#25]

**Comment by gvne** [comment]
Hi @Jstonebeats1, if you want to use spleeter in a terminal but don't want to install deezer's conda environment, take a look at the [spleet](https://github.com/gvne/spleet/releases) project. Pre-built should run up to 11kHz but building it to support 16kHz shouldn't be a problem if you are familiar with c++ and cmake.

If you just want to run spleeter and are fine with using conda, you should check out the spleeter [documentation](https://github.com/deezer/spleeter/wiki/1.-Installation). It is quite clear. They also provide a gitter to help you get started.

**Comment by Jstonebeats1** [comment]
Hi, I’m not sure about conda or deezer.
I am using docker
Just trying to find out the exact command I would have to type in to the terminal 
To make spleeter run in 16kHz mode.
I’m not that good with computers.

**Comment by gvne** [comment]
I see. You should check [this](https://github.com/deezer/spleeter/wiki/2.-Getting-started#run-container) out then. Have you tried something like this ?
```
docker run -v [your output folder]:/output researchdeezer/spleeter separate -i [your input file] -o /output -p spleeter:4stems-16kHz
```

**Comment by Jstonebeats1** [comment]
Hi,

Do you mean type or copy and paste all this into the command line?

docker run -v [your output folder]:/output researchdeezer/spleeter
separate -i [your input file] -o /output -p spleeter:4stems-16kHz

**Comment by Jstonebeats1** [comment]
it says this
