### ISSUE TITLE
Bind Spleeter In Android App

### ISSUE THREAD

**Issue by oluwabajio** [gvne/spleeterpp#27]
Hello,

i would love to use spleeter in one of my android apps (java).

i have successfully implemented Deezer spleeter on my server (aivocalremover.com), but I would like to find out if its possible to bind your C++ spleter project on my android java app.

**Comment by gvne** [comment]
Hi @oluwabajio I'm afraid the tools I'm using at the moment won't port properly to android. The first huge step in that way would be use TFLite as stated in https://github.com/gvne/spleeterpp/issues/26.
