### ISSUE TITLE
Add windows build instructions

### ISSUE THREAD

**Issue by gvne** [gvne/spleeterpp#3]

**Comment by gvne** [comment]
See this: https://joe-antognini.github.io/machine-learning/build-windows-tf for `tensorflow_cc`

**Comment by gvne** [comment]
I successfully built tensorflow_cc on windows following this https://www.tensorflow.org/install/source_windows.  
I still have issues with using the built libraries though

**Comment by UtkarshBhatthere** [comment]
Hey! Can I be of some help ?

**Comment by gvne** [comment]
That would be awesome ! Did you have a chance to build the tensorflow_cc on windows ?

**Comment by gvne** [comment]
After much struggle I finally found a way to build the library and export the right symbols (see the doc here: https://spleeterpp.readthedocs.io/en/latest/build.html#tensorflow-cc-for-windows).

That being said, the test does not pass. I will have to investigate it.

**Comment by gvne** [comment]
Turns out the exception in tests was due to a known bug: https://github.com/tensorflow/tensorflow/issues/17778#issuecomment-384816014

Apparently the memory layout of the  std::string is different in debug and release with msvc. Compiling in release mode fixes the issue.
