### ISSUE TITLE
Build failed in windows 10 using MingW

### ISSUE THREAD

**Issue by MBSadeghzadeh** [gvne/spleeterpp#31]
Cloned last version of code and built it with Cmake configured with MingW on Windows 10, I get this error:
````CMake Error at cmake/add_tensorflow.cmake:70 (find_library):
  Could not find tensorflow_framework_lib using the following names:
  tensorflow_framework
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)
````

Is there anything wrong with add_tensorflow when we are on windows using MingW instead of MSVC?

**Comment by gvne** [comment]
Hi @MBSadeghzadeh, I have to admit that I'm not use to work with mingw. Is this error only related to #32 ?

**Comment by MBSadeghzadeh** [comment]
Hi @gvne . Yes, it is related to [#32](https://github.com/gvne/spleeterpp/pull/32) and I fixed it.
