### ISSUE TITLE
Include prebuilt version of tensorflow_cc

### ISSUE THREAD

**Issue by flocked** [gvne/spleeterpp#6]
It would be great if you could upload a pre built tensorflow_cc library. I tried to compile it on my slow Mac. It was running for hours and at some point crashed.

Thanks :)

**Comment by gvne** [comment]
Hi @flocked, I just uploaded the osx and linux version of the library. If the TENSORFLOW_CC_INSTALL_DIR isn't set, cmake downloads it.
