### ISSUE TITLE
Problems including in project

### ISSUE THREAD

**Issue by MeijisIrlnd** [gvne/spleeterpp#7]
Hiya, built this according to the steps but having a little bit of trouble with the linker and compiler (macOs 10.13.6), was wondering if maybe you could post the flags needed to build in g++? thanks in advance!

**Comment by MeijisIrlnd** [comment]
Edit: Fixed this I was including a version of eigen different to the one in tensorflow_cc, thanks for porting this it looks great!

**Comment by gvne** [comment]
You're welcome. Thank you for the feedback. Happy to hear you can make use of this !
